//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeListen.Data
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    
            [KnownType(typeof(Location))]
            [KnownType(typeof(Song))]
            [KnownType(typeof(LocationPlaylist))]
    public partial class LocationCatalog
    {
        public LocationCatalog()
        {
            this.LocationPlaylists = new HashSet<LocationPlaylist>();
        }
    
        public int LocationCatalogId { get; set; }
        public int SongId { get; set; }
        public int LocationId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Song Song { get; set; }
        public virtual ICollection<LocationPlaylist> LocationPlaylists { get; set; }
    }
}
