//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeListen.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.FavoriteSongs = new HashSet<FavoriteSong>();
            this.LocationPlaylists = new HashSet<LocationPlaylist>();
            this.Songs = new HashSet<Song>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<FavoriteSong> FavoriteSongs { get; set; }
        public virtual ICollection<LocationPlaylist> LocationPlaylists { get; set; }
        public virtual ICollection<Song> Songs { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
